const puppeteer = require('puppeteer');

function buildRecipeHTML(recipe, servings) {
  const tags = recipe.recipe_tags?.map(rt => rt.tags?.name).filter(Boolean).join(', ') || '';
  const difficulty = recipe.difficulty
    ? recipe.difficulty.charAt(0).toUpperCase() + recipe.difficulty.slice(1)
    : '';

  const ingredientsHTML = recipe.ingredients
    .map(ing => `<li>${ing.quantity} ${ing.unit} ${ing.name}</li>`)
    .join('');

  const stepsHTML = recipe.steps
    .map(step => `
      <div class="step">
        <div class="step-number">${step.step_number}</div>
        <div class="step-content">
          <p>${step.description}</p>
          ${step.photo_url ? `<img src="${step.photo_url}" alt="Step ${step.step_number}" />` : ''}
        </div>
      </div>
    `)
    .join('');

  return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&family=Inter:wght@400;500&display=swap');

    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; color: #2D2D2D; background: #FDF8F0; padding: 40px; }

    .cover img { width: 100%; height: 300px; object-fit: cover; border-radius: 12px; margin-bottom: 24px; }

    h1 { font-family: 'Playfair Display', serif; font-size: 32px; color: #2D2D2D; margin-bottom: 8px; }

    .meta { display: flex; gap: 16px; color: #666; font-size: 14px; margin-bottom: 12px; flex-wrap: wrap; }
    .meta span { display: flex; align-items: center; gap: 4px; }

    .tags { margin-bottom: 24px; }
    .tag { display: inline-block; background: #C2614F; color: white; font-size: 12px;
           padding: 3px 10px; border-radius: 20px; margin-right: 6px; }

    h2 { font-family: 'Playfair Display', serif; font-size: 22px; margin: 24px 0 12px; border-bottom: 2px solid #C2614F; padding-bottom: 6px; }

    ul { list-style: none; padding: 0; }
    ul li { padding: 6px 0; border-bottom: 1px solid #EEE; font-size: 15px; }

    .step { display: flex; gap: 16px; margin-bottom: 20px; }
    .step-number { background: #C2614F; color: white; width: 32px; height: 32px; border-radius: 50%;
                   display: flex; align-items: center; justify-content: center; font-weight: bold; flex-shrink: 0; }
    .step-content p { font-size: 15px; line-height: 1.6; }
    .step-content img { width: 100%; max-height: 200px; object-fit: cover; border-radius: 8px; margin-top: 10px; }

    .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; border-top: 1px solid #EEE; padding-top: 16px; }
  </style>
</head>
<body>
  ${recipe.cover_photo_url ? `<div class="cover"><img src="${recipe.cover_photo_url}" alt="${recipe.title}" /></div>` : ''}
  <h1>${recipe.title}</h1>
  <div class="meta">
    <span>By ${recipe.users?.display_name || 'Unknown'}</span>
    ${difficulty ? `<span>· ${difficulty}</span>` : ''}
    ${recipe.cooking_time_minutes ? `<span>· ${recipe.cooking_time_minutes} min</span>` : ''}
    <span>· ${servings} servings</span>
    ${recipe.cuisine ? `<span>· ${recipe.cuisine}</span>` : ''}
  </div>
  ${tags ? `<div class="tags">${tags.split(', ').map(t => `<span class="tag">${t}</span>`).join('')}</div>` : ''}
  <p style="color:#555; line-height:1.6; margin-bottom:16px;">${recipe.description}</p>

  <h2>Ingredients</h2>
  <ul>${ingredientsHTML}</ul>

  <h2>Instructions</h2>
  ${stepsHTML}

  <div class="footer">Generated by RecipeVault · recipevault.app</div>
</body>
</html>
  `;
}

async function generateRecipePDF(recipe, servings) {
  const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox', '--disable-setuid-sandbox'] });
  const page = await browser.newPage();

  const html = buildRecipeHTML(recipe, servings);
  await page.setContent(html, { waitUntil: 'networkidle0' });

  const pdfBuffer = await page.pdf({
    format: 'A4',
    margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' },
    printBackground: true
  });

  await browser.close();
  return pdfBuffer;
}

module.exports = { generateRecipePDF };
